server:
  port: 8080
spring:
  application:
    name: Stock Azul e Rosa
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    user:
      name: admin
      password: admin
security:
  jwt-secret: ${JWT_SECRET}
  jwt-expire-hours: ${JWT_EXPIRED_TIME}



springdoc:
  swagger-ui:
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
